name: Keep Render Awake

on:
  schedule:
    - cron: '*/14 13-18 * * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: curl -sSf https://mda-zcnm.onrender.com/ > /dev/null